#!/usr/bin/env python3
"""Derive configs/demo_facts.json — the numbers the demo page shows. Costs $0.00.

WHY A GENERATED FILE. The page needs a handful of headline figures (the API cost per
clause, the INT8 collapse, the escalation result). `results/` is gitignored except for the
summaries and is NOT copied into the serving image, and typing the numbers into HTML would
put unsourced constants on the most public surface in the project. So they are derived here
from the committed result summaries and from configs/costs.yaml, each with a `source` naming
where it came from, and the result is committed and shipped with the image.

Nothing here computes a cost from a rate card by hand: the API figure is measured spend
divided by measured requests, straight out of the ledger.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

R = Path("results")
OUT = Path("configs/demo_facts.json")


def main() -> int:
    cost = json.loads((R / "cost_per_1k.json").read_text())
    isa = json.loads((R / "isa_matrix.json").read_text())
    esc = json.loads((R / "served_config_escalation.json").read_text())
    t0 = json.loads((R / "fp32_local_onnx_ce10ep_seed1.json").read_text())["metrics"]

    api = cost["api"]["claude-sonnet-5"]
    mf = {r["isa"]: r for r in isa["test_3000_macro_f1"]["rows"]}
    arm = mf["macOS arm64"]
    x86 = mf["Linux x86 (Kaggle Xeon)"]

    facts = {
        "_what": "Figures shown on the demo page. Generated by scripts/build_demo_facts.py.",
        "_regenerate": "python scripts/build_demo_facts.py",

        "api_comparator": {
            "model": "claude-sonnet-5",
            "usd_per_clause": api["usd_per_1k"] / 1000.0,
            "usd_per_1k": api["usd_per_1k"],
            "basis": ("MEASURED mean over the 3,000-clause Stage 1 batch, Batch API with "
                      "prompt caching. Not an estimate for any particular clause: a "
                      "per-clause Claude figure needs that model's own count_tokens "
                      "(hard rule 9), which costs an API call."),
            "n_requests": api["n_requests"],
            "cost_usd_total": api["cost_usd"],
            "source": "results/spend_ledger.jsonl via results/cost_per_1k.json",
        },

        "tier0": {
            "macro_f1": t0["macro_f1"],
            "accuracy": t0["accuracy"],
            "split": "test_3000",
            "source": "results/fp32_local_onnx_ce10ep_seed1.json",
        },

        "int8_collapse": {
            "caption": ("Same weights, same 3,000 rows. INT8 falls to chance on a CPU "
                        "without AVX-512 VNNI, and raises no error doing it."),
            "rows": [
                {"isa": "macOS arm64", "vnni": None,
                 "fp32": arm["fp32"], "int8": arm["int8"]},
                {"isa": "Linux x86 (Xeon)", "vnni": False,
                 "fp32": x86["fp32"], "int8": x86["int8"]},
            ],
            "source": "results/isa_matrix.json",
        },

        "escalation": {
            "delta": esc["delta"],
            "ci_low": esc["bootstrap"]["lo"],
            "ci_high": esc["bootstrap"]["hi"],
            "p": esc["bootstrap"]["p_sign"],
            "n_rows": esc["n_rows"],
            "n_escalated": esc["n_escalated"],
            "tier0_accuracy_on_escalated": esc["mcnemar_escalated_rows"]["tier0_accuracy"],
            "api_accuracy_on_escalated": esc["mcnemar_escalated_rows"]["api_accuracy"],
            "in_sample": esc["in_sample"],
            "source": "results/served_config_escalation.json",
        },
    }
    OUT.write_text(json.dumps(facts, indent=2) + "\n")
    print(f"wrote {OUT}")
    print(f"  api ${facts['api_comparator']['usd_per_clause']:.8f}/clause "
          f"(measured over {api['n_requests']:,} clauses)")
    print(f"  int8 on non-VNNI x86: {x86['int8']}")
    print(f"  escalation delta {esc['delta']:+.6f} "
          f"CI [{esc['bootstrap']['lo']:+.4f}, {esc['bootstrap']['hi']:+.4f}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
